'use client';
import {useState,useEffect,useRef} from 'react';
import {Sprout,ShoppingBag,Leaf,Carrot,MapPin,Flower2,Utensils,Recycle,CloudCheck,CalendarDays,ChartPie,Check,RefreshCw,Printer} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import './kitchen.css';
import {apiFetch} from '@/lib/api-client';
type Access='1'|'2';
type Day={id:string,classId:string,date:string,dish:string,answers:(boolean|null)[],version:number};
const qs=['Wir vermeiden Plastikmüll beim Einkauf.','Wir verzichten auf Fleisch.','Wir kaufen Obst und Gemüse.','Wir kaufen Bio-Lebensmittel.','Wir kaufen Lebensmittel aus der Region.','Wir nutzen Zutaten aus dem Schulgarten.','Wir nutzen Reste aus der Schülerspeisung.','Wir vermeiden Reste.'];
const names=['Plastik vermeiden','Ohne Fleisch','Obst & Gemüse','Bio-Lebensmittel','Aus der Region','Aus dem Schulgarten','Reste verwenden','Reste vermeiden'];
const icons=[ShoppingBag,Leaf,Carrot,Sprout,MapPin,Flower2,Utensils,Recycle];
function Picker({label,value,set,options}:{label:string,value:string,set:(v:string)=>void,options:string[][]}){return <div className="field"><span>{label}</span><Select value={value} onValueChange={set}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></div>}
function Ring({values}:{values:(boolean|null)[]}){const yes=values.filter(x=>x===true).length,no=values.filter(x=>x===false).length,total=yes+no,p=total?yes/total*100:0;return <><div className="ring" role="img" aria-label={`${yes} Ja, ${no} Nein, ${values.length-total} offen`} ><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="44" fill="none" stroke={total?'#ed8348':'#eaf1f4'} strokeWidth="12"/>{total>0&&<circle cx="50" cy="50" r="44" fill="none" stroke="#00866a" strokeWidth="12" pathLength="100" strokeDasharray={`${p} ${100-p}`} transform="rotate(-90 50 50)"/>}</svg><div><strong>{total?Math.round(p)+'%':'–'}</strong><span>mit Ja beantwortet</span></div></div><div className="legend"><span><i className="yesdot"/>{yes} Ja</span><span><i className="nodot"/>{no} Nein</span></div><p className="chartnote">{values.length-total} offen · Offene Fragen zählen nicht als Nein.</p></>}
function Login({onLogin,locked}:{onLogin:(a:Access)=>void,locked?:Access}){
 const [access,setAccess]=useState<Access>(locked||'1'),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const response=await apiFetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({access,code})});const data=await response.json() as {access:Access|null,error?:string};if(!response.ok)throw Error(data.error||'Anmelden fehlgeschlagen.');setCode('');if(!data.access)throw Error('Zugang ungültig.');onLogin(data.access);}catch(e){setError(e instanceof Error?e.message:'Anmelden fehlgeschlagen.');}finally{setBusy(false)}}
 return <div className="kitchen login-page"><main><section className="panel login-panel"><div className="brand"><span><Sprout/></span>Heute kochen wir</div><h1>{locked?'Bitte erneut anmelden':'Willkommen in unserer Schulküche'}</h1><p>{locked?'Deine Eingaben bleiben erhalten. Melde dich mit demselben Zugang erneut an.':'Wähle deine Klasse und gib das Passwort ein.'}</p><form onSubmit={submit}>{locked?<p><strong>{'WS '+locked}</strong></p>:<Picker label="Deine Klasse" value={access} set={v=>{setAccess(v as Access);setError('')}} options={ [['1','WS 1'],['2','WS 2']]}/>}<label className="field">Passwort<input type="password" value={code} onChange={e=>setCode(e.target.value)} autoComplete="current-password" autoCapitalize="none" spellCheck={false} maxLength={100} required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="print-button" disabled={busy||!code.trim()}>{busy?'Wird geprüft …':'Los geht’s'}</button></form><p className="login-note">Kein persönliches Konto nötig. Bitte nach der Arbeit abmelden.</p></section></main></div>
}
export default function AccessGate(){
 const[access,setAccess]=useState<Access|null>(null),[checking,setChecking]=useState(true),[error,setError]=useState(false);
 async function check(){setChecking(true);setError(false);try{const response=await apiFetch('/api/access',{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json() as {access:Access|null,error?:string};setAccess(data.access);}catch{setError(true)}finally{setChecking(false)}}
 useEffect(()=>{void check()},[]);
 if(checking)return <div className="kitchen login-page"><main><p role="status">Zugang wird geladen …</p></main></div>;
 if(error)return <div className="kitchen login-page"><main><p role="alert">Der Zugang konnte nicht geladen werden.</p><button className="print-button" onClick={()=>void check()}>Erneut versuchen</button></main></div>;
 return access?<Home access={access} onLogout={()=>setAccess(null)}/>:<Login onLogin={setAccess}/>;
}
function Home({access,onLogout}:{access:Access,onLogout:()=>void}){const[records,setRecords]=useState<Record<string,Day>>({}),[drafts,setDrafts]=useState<Record<string,Day>>({}),[cls,setCls]=useState<string>(access),[date,setDate]=useState(''),[tab,setTab]=useState('entry'),[range,setRange]=useState('all'),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('Daten werden geladen …'),[conflict,setConflict]=useState(false);const[expired,setExpired]=useState(false);const apiRef=useRef<()=>unknown>(()=>({}));
 async function load(){setBusy(true);setError('');try{const r=await apiFetch('/api/records',{cache:'no-store'});if(r.status===401){setExpired(true);throw Error('Bitte erneut anmelden. Deine Eingaben bleiben erhalten.');}const data=await r.json() as {records:Day[],error?:string,conflict?:boolean};if(!r.ok)throw Error(data.error||'Laden fehlgeschlagen.');setRecords(Object.fromEntries(data.records.map((d:Day)=>[d.id,d])));setLoaded(true);setStatus('Online-Daten geladen');return data.records as Day[];}catch(e){setError(e instanceof Error?e.message:'Laden fehlgeschlagen.');return null;}finally{setBusy(false);}}
 useEffect(()=>{setDate(new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date()));void load();},[]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(Object.keys(drafts).length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[drafts]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_cooking_summary',description:'Liest die aktuelle gespeicherte Auswertung und die Anzahl ungespeicherter Kochtage.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Keine Parameter erwartet.');return apiRef.current();}},{signal:lifecycle.signal})).catch(console.error);}catch(e){console.error(e)}return()=>lifecycle.abort()},[]);
 const id=cls+'|'+date,current=drafts[id]||records[id]||{id,classId:cls,date,dish:'',answers:Array(8).fill(null),version:0},count=current.answers.filter(x=>x!==null).length;
 function changeDish(dish:string){setDrafts(p=>({...p,[id]:{...current,dish}}));setStatus('Änderungen noch nicht gespeichert');}
 function choose(i:number,v:string){const answers=[...current.answers];answers[i]=v==='open'?null:v==='yes';setDrafts(p=>({...p,[id]:{...current,answers}}));setStatus('Änderungen noch nicht gespeichert');}
 async function save(all:boolean){const rows=all?Object.values(drafts):[current];if(!rows.length||!date)return;setBusy(true);setError('');try{const r=await apiFetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({records:rows})});if(r.status===401){setExpired(true);throw Error('Bitte erneut anmelden. Deine Eingaben bleiben erhalten.');}const data=await r.json() as {records:Day[],error?:string,conflict?:boolean};if(!r.ok){setConflict(!!data.conflict);throw Error(data.error||'Speichern fehlgeschlagen.');}setRecords(p=>({...p,...Object.fromEntries(data.records.map((d:Day)=>[d.id,d]))}));setDrafts(p=>{const copy={...p};rows.forEach(d=>delete copy[d.id]);return copy});setConflict(false);setStatus(`${rows.length===1?'Kochtag':rows.length+' Kochtage'} online gespeichert ✓`);}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen.');}finally{setBusy(false);}}
 async function compare(){const latest=await load();if(!latest)return;setDrafts(p=>Object.fromEntries(Object.entries(p).map(([k,d])=>[k,{...d,version:latest.find(x=>x.id===k)?.version||0}])));setConflict(false);setStatus('Aktuellen Stand geladen. Vergleiche deine Eingaben vor erneutem Speichern.');}
 const selected=Object.values(records).filter(d=>{if(d.classId!==access)return false;if(range==='day')return d.date===date;if(range==='month')return d.date.slice(0,7)===date.slice(0,7);if(range==='week'){const start=new Date(date+'T12:00:00Z');start.setUTCDate(start.getUTCDate()-(start.getUTCDay()+6)%7);const diff=(+new Date(d.date+'T12:00:00Z')-+start)/86400000;return diff>=0&&diff<7}return true});
 const formatDate=(value:string)=>value?new Date(value+'T12:00:00Z').toLocaleDateString('de-DE',{timeZone:'UTC'}):'–';
 const periodLabel=(()=>{if(range==='all')return 'Gesamter Zeitraum';if(range==='day')return formatDate(date);if(range==='month')return date?new Date(date+'T12:00:00Z').toLocaleDateString('de-DE',{month:'long',year:'numeric',timeZone:'UTC'}):'–';if(!date)return '–';const start=new Date(date+'T12:00:00Z');start.setUTCDate(start.getUTCDate()-(start.getUTCDay()+6)%7);const end=new Date(start);end.setUTCDate(end.getUTCDate()+6);return formatDate(start.toISOString().slice(0,10))+' – '+formatDate(end.toISOString().slice(0,10));})();
 apiRef.current=()=>({savedDays:selected.length,yes:selected.flatMap(d=>d.answers).filter(x=>x===true).length,no:selected.flatMap(d=>d.answers).filter(x=>x===false).length,unsavedDays:Object.keys(drafts).length});
 async function logout(){setBusy(true);setError('');try{const r=await apiFetch('/api/access',{method:'DELETE'});if(!r.ok)throw Error('Abmelden fehlgeschlagen. Bitte erneut versuchen.');setRecords({});setDrafts({});onLogout();}catch(e){setError(e instanceof Error?e.message:'Abmelden fehlgeschlagen.')}finally{setBusy(false)}}
 if(expired)return <Login locked={access} onLogin={()=>{setExpired(false);void load()}}/>;
 return <div className="kitchen"><header><a href="./" className="brand"><span><Sprout/></span>Heute kochen wir</a><span className="cloud"><CloudCheck size={18}/> {'WS '+access}</span><button className="logout-button" disabled={busy||Object.keys(drafts).length>0} title={Object.keys(drafts).length?'Bitte zuerst deine Änderungen speichern.':'Von diesem Gerät abmelden'} onClick={()=>void logout()}>Abmelden</button></header><main><div className="intro"><div><span className="eyebrow">UNSERE SCHULKÜCHE</span><h1>Gemeinsam kochen.<br/>Bewusst genießen.</h1><p>Unser Blick auf gesundes und nachhaltiges Kochen.</p></div><Sprout className="hero-icon" aria-hidden="true"/></div><Tabs value={tab} onValueChange={setTab}><div className="toolbar"><Picker label="Unsere Klasse" value={cls} set={setCls} options={[[access,'WS '+access]]}/><TabsList className="tabbar"><TabsTrigger value="entry"><Check/>Eintragen</TabsTrigger><TabsTrigger value="days"><CalendarDays/>Kochtage</TabsTrigger><TabsTrigger value="stats"><ChartPie/>Auswertung</TabsTrigger></TabsList><button className="refresh" disabled={busy} onClick={()=>void load()} aria-label="Online-Daten aktualisieren"><RefreshCw size={18}/></button></div><div className="notice" role="status">{busy?'Verbindung zur Online-Datenbank …':status}{Object.keys(drafts).length>0&&` · ${Object.keys(drafts).length} ungespeichert`}</div>{error&&<div className="error" role="alert">{error} {conflict?<button onClick={()=>void compare()}>Aktuellen Stand zum Vergleichen laden</button>:<button disabled={busy} onClick={()=>void load()}>Erneut laden</button>}</div>}
 <TabsContent value="entry"><div className="datebar"><label className="field">Kochtag<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><div className="progressbox"><span>{count} von 8 beantwortet</span><Progress value={count/8*100}/></div></div><div className="columns"><section className="panel"><label className="field dish-field">Was haben wir gekocht?<input type="text" value={current.dish||''} onChange={e=>changeDish(e.target.value)} maxLength={120} disabled={busy||!loaded||!date} placeholder="Zum Beispiel: Gemüse-Lasagne"/><span className="subtle">Das Gericht erscheint in eurer Auswertung.</span></label>{drafts[id]&&records[id]&&drafts[id].dish!==records[id].dish&&<p className="subtle">Zuletzt online: {records[id].dish||'Kein Gericht eingetragen'}</p>}<h2>So haben wir heute gekocht</h2><fieldset disabled={busy||!loaded||!date}>{qs.map((q,i)=>{const Icon=icons[i],v=current.answers[i];return <div className="question" key={q}><span className="qicon"><Icon size={22}/></span><div className="questionbody"><span id={'q'+i}>{q}</span><RadioGroup className="answerrow" aria-labelledby={'q'+i} value={v===null?'open':v?'yes':'no'} onValueChange={v=>choose(i,v)}>{(i===5?[['yes','Ja'],['no','Nein'],['open','Offen']]:[['yes','Ja'],['no','Nein']]).map(([a,t])=><label className={'answer '+a+(a===(v===null?'open':v?'yes':'no')?' chosen':'')} key={a}><RadioGroupItem value={a}/>{t}</label>)}</RadioGroup>{drafts[id]&&records[id]&&drafts[id].answers[i]!==records[id].answers[i]&&<small>Zuletzt online: {records[id].answers[i]===null?'offen':records[id].answers[i]?'Ja':'Nein'}</small>}</div></div>})}</fieldset><div className="actions"><button className="primary" disabled={busy||!loaded||!date||conflict} onClick={()=>void save(false)}>Tag speichern</button><button disabled={busy||!loaded||!Object.keys(drafts).length||conflict} onClick={()=>void save(true)}>Alle Änderungen speichern</button></div></section><aside className="panel"><h2>Unser Kochtag</h2>{current.dish&&<p className="dish-title">{current.dish}</p>}<span className="subtle">{drafts[id]?'Vorschau deiner Eingaben':records[id]?'Gespeicherter Stand':'Neuer Kochtag'}</span><Ring values={current.answers}/><div className="asidefoot"><Sprout size={20}/><span>Jedes bewusste Ja zählt.</span></div></aside></div></TabsContent>
 <TabsContent value="days"><section className="panel"><h2>Unsere Kochtage</h2>{Object.values({...records,...drafts}).filter(d=>d.classId===cls).sort((a,b)=>b.date.localeCompare(a.date)).map(d=><button className="dayrow" key={d.id} onClick={()=>{setDate(d.date);setTab('entry')}}><span>{new Date(d.date+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}<strong className="day-dish">{d.dish||'Kein Gericht eingetragen'}</strong></span><span>{d.answers.filter(x=>x!==null).length}/8 beantwortet · {drafts[d.id]?'ungespeichert':'online gespeichert'}</span></button>)}{!Object.values({...records,...drafts}).some(d=>d.classId===cls)&&<p>Noch keine Kochtage. Füllt eure erste Checkliste unter „Eintragen“ aus.</p>}</section></TabsContent>
 <TabsContent value="stats" className="stats-report"><div className="toolbar"><Picker label="Zeitraum" value={range} set={setRange} options={ [['all','Gesamter Zeitraum'],['day','Ausgewählter Tag'],['week','Woche des ausgewählten Tages'],['month','Monat des ausgewählten Tages']]}/><label className="field">Bezugsdatum<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="print-button" disabled={busy||!loaded||(range!=='all'&&!date)} onClick={()=>window.print()}><Printer size={19}/>Auswertung drucken</button></div><div className="report-heading"><h2>Heute kochen wir · Auswertung</h2><p><strong>{'WS '+access}</strong> · {periodLabel}</p><p>{selected.length} gespeicherte Kochtage · Stand: {new Date().toLocaleDateString('de-DE')}</p></div><div className="columns"><section className="panel"><h2>Was gelingt uns schon?</h2>{names.map((n,i)=>{const a=selected.map(d=>d.answers[i]).filter(x=>x!==null),yes=a.filter(Boolean).length,p=a.length?Math.round(yes/a.length*100):0;return <div className="barrow" key={n}><div><span>{n}</span><span>{a.length?p+' %':'–'} · {yes}/{a.length}</span></div><div className="track"><div style={{width:p+'%'}}/></div></div>})}</section><aside className="panel"><h2>Unsere Antworten</h2><span className="subtle">{selected.length} gespeicherte Kochtage</span><Ring values={selected.flatMap(d=>d.answers)}/></aside></div><section className="panel meal-history"><h2>Das haben wir gekocht</h2><p className="subtle">Gerichte im ausgewählten Zeitraum</p>{selected.length===0?<p>Noch keine Kochtage in dieser Auswahl.</p>:<div className="meal-table-wrap"><table className="meal-table"><thead><tr><th>Datum</th><th>Klasse</th><th>Gericht</th></tr></thead><tbody>{[...selected].sort((a,b)=>b.date.localeCompare(a.date)||a.classId.localeCompare(b.classId)).map(d=><tr key={d.id}><td>{formatDate(d.date)}</td><td>WS {d.classId}</td><td>{d.dish||'Kein Gericht eingetragen'}</td></tr>)}</tbody></table></div>}</section></TabsContent></Tabs><footer>Wir kochen nachhaltig und gesund.</footer></main></div>
}
